services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/ssd/arr/radarr/config:/config
      - /mnt/ssd/arr/radarr/movies:/data/movies
      - /mnt/ssd/arr/qbittorrent/downloads:/downloads
    # ports:
    #   - 7878:7878
    networks:
      - proxy
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/ssd/arr/sonarr/config:/config
      - /mnt/ssd/arr/sonarr/tvseries:/data/tvshows
      - /mnt/ssd/arr/qbittorrent/downloads:/downloads
    # ports:
    #   - 8989:8989
    networks:
      - proxy
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/ssd/arr/prowlarr/config:/config
    # ports:
    #   - 9696:9696
    networks:
      - proxy
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/ssd/arr/bazarr/config:/config
      - /mnt/ssd/arr/radarr/movies:/data/movies
      - /mnt/ssd/arr/sonarr/tvseries:/data/tvshows
    # ports:
    #   - 6767:6767
    networks:
      - proxy
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/ssd/arr/lidarr/config:/config
      - /mnt/ssd/arr/lidarr/music:/data/music
      - /mnt/ssd/arr/qbittorrent/downloads:/downloads
    ports:
      - 18686:8686
  #   restart: unless-stopped

  # readarr: # depricated
  #   image: lscr.io/linuxserver/readarr:amd64-nightly-0.4.0.2593-ls334
  #   container_name: readarr
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Etc/UTC
  #   volumes:
  #     - /mnt/ssd/arr/readarr/config:/config
  #     - /mnt/ssd/arr/readarr/books:/data/books
  #     - /mnt/ssd/arr/qbittorrent/downloads:/downloads
  #   ports:
  #     - 18787:8787
  #   restart: unless-stopped

  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    restart: unless-stopped
    environment:
      - TZ=Etc/UTC
    volumes:
      - /mnt/ssd/arr/homarr/config:/app/data/configs
      - /mnt/ssd/arr/homarr/icons:/app/public/icons
      - /mnt/ssd/arr/homarr/data:/data
  #   ports:
  #     - 17575:7575

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /mnt/ssd/arr/qbittorrent/config:/config
      - /mnt/ssd/arr/qbittorrent/downloads:/downloads
    ports:
      # - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    networks:
      - proxy
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    runtime: nvidia

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    volumes:
      - /mnt/ssd/arr/jellyfin/config:/config
      - /mnt/ssd/arr/sonarr/tvseries:/data/tvshows
      - /mnt/ssd/arr/radarr/movies:/data/movies
      - /mnt/ssd/arr/readarr/books:/data/books
      - /mnt/ssd/arr/lidarr/music:/data/music
    ports:
      # - 8096:8096
      - 8920:8920
      - 7359:7359/udp # discovery
      - 1900:1900/udp # SSDP (if you use DLNA)
    networks:
      - proxy
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           capabilities: ["gpu"]
    #           device_ids: ["0"]
    restart: unless-stopped

  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    container_name: seerr
    init: true
    environment:
      - LOG_LEVEL=debug
      - TZ=Etc/UTC
      - PORT=5055
    dns:
      - 1.1.1.1
      - 8.8.8.8
    # ports:
    #   - 5055:5055
    networks:
      - proxy
    volumes:
      - /mnt/ssd/arr/seerr/config:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # Optional: set to "docker" for clearer networking in some setups
      - VERSION=docker
      # Optional: if you want to claim the server automatically, add your claim token:
      - PLEX_CLAIM=claim-b84Qd4tUo891Bs6yBGRc
    volumes:
      - /mnt/ssd/arr/plex/config:/config
      # Plex transcode scratch (optional but recommended on SSD)
      - /mnt/ssd/arr/plex/transcode:/transcode
      # Keep the same mounts you already use so paths match Radarr/Sonarr/Bazarr
      - /mnt/ssd/arr/sonarr/tvseries:/data/tvshows
      - /mnt/ssd/arr/radarr/movies:/data/movies
      - /mnt/ssd/arr/readarr/books:/data/books
      - /mnt/ssd/arr/lidarr/music:/data/music
    ports:
      # - 32400:32400     # Plex Web
      # Optional (recommended) discovery/casting on LAN:
      - 1900:1900/udp
      - 5353:5353/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469 # DLNA (only if you use it)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]
              device_ids: ["0"]
    restart: unless-stopped

networks:
  proxy:
    external: true
